== Managed beans, Scopes and Contexts

We already saw what a _managed bean_ in CDI. It is simply a bean that is created by CDI and provided to our code, at the time and places where we need it. We saw that CDI was able to create a bean in order to inject it in a special place in our code, for instance, a field, as long as it has a way to create that bean. We also saw the very sophisticated ways CDI has to associate an injection point and an implementing class, and how CDI can build the needed instances on its own.

There is still one point that we did not talk about, which is the following. Once CDI has created an instance of a particular bean, what should it do with it? If another injection point needs the same type of bean (in the CDI sense), can the same object be injected, or should CDI create another one? The fact is: there is no single answer to this question. It depends on the bean, and what your application is doing with it.

Suppose that we are creating a web application, and this injected object is the shopping cart. If we are dealing with a returning customer, we certainly want to use the same shopping cart. So in that case, we want CDI to inject the same object, so that our customer can continue her shopping.

But if we detect that the customer is another one, we certainly do not want the first shopping cart to be injected. We want another one, newly created.

The difference between those two use cases is in fact the context in which those two pieces of code are executed. The context here is a session context, in the HTTP sense. The shopping cart bean is bound to the session context, and its session ID, that acts as a primary key for this context. What we want, is for CDI to handle this context automatically for us, deal with the details, and just inject the right shopping cart bean in the right place.

We can see on this simple example, that to identify a cart bean, we need to provide an HTTP Session. We thus say that the cart bean is _bound_ to the HTTP Session context. This context gives the boundaries of this bean. Requesting a shopping cart without telling what HTTP Session this cart is bound would not make any sense.

In the CDI world, a scope is a class annotated with the `@Scope` annotation. There are restriction on this class, that we are going to see later in this part.

A context, on the other hand, is an interface, that should be implemented. Any object that implements the `Context` interface is said to be a context object, that models the context of CDI beans.

There is a third notion to understand now, which is the notion of `Contextual` bean. In fact, in CDI, any bean is bound to a context, thus a _contextual_ bean. This interface defines how a bean is created and destroyed, as we are going to see it.

