
=== The notion of Bean archive

We introduced the notion of bean archive in our first example, without defining it. The object of this paragraph is to precisely define what a bean archive is in the CDI context. As CDI works in both the Java SE world and the Java EE world, this notion of bean archive is defined in both worlds, with some differences.

This paragraph covers everything you need to know about bean archives in the CDI sense. It is a set of definitions to fully understand how bean archives work in CDI, both in the Java SE space and the Java EE space.

==== The purpose of a bean archive

What is the purpose of a bean archive? Well, a CDI container analyzes the content of all the bean archives it knows, looking for its supported annotations and descriptors. It then builds an object graph and gather all the information it needs so that our application can work. A JAR or any other archive is the most general sense that is not a bean archive is not analyzed by CDI.

Let us suppose for now that a bean archive is a simple JAR. Indeed a JAR can be a bean archive, but other Java containers can be bean archives too.

So a bean archive is a very important notion in CDI: it defines where CDI is going to look for the information it needs for our application to work properly.

In fact, most of the time, when you get a CDI error telling you that some information is not known (a producer for instance), or has not been discovered, it comes from an archive problem: most probably the JAR with the faulty bean has not been analyzed by CDI. So understanding how bean archives work is important prior to understanding anything else in CDI.

We must consider two cases: the case of a CDI application that is part of a Java EE application, and the case of a standalone CDI application.

A bean archive is built on top of a Java archive. In all cases, a Java archive is a classical Java language notion. Such an archive can be:

* a directory on the classpath or a JAR file in the Java SE world, or
* an EAR, a WAR, or a RAR in the Java EE world.

Those are the classical examples of archives. But it can also be the `WEB-INF/classes` special directory of a web archive. This special directory can be in a WAR file, but not necessarily.

So what makes a Java archive, a CDI bean archive? The answer is simple: the presence of a special file, the `beans.xml` file. Where should this file be put? There are several places for it. In the Java SE world, it should be put in the `META-INF` directory of an archive. Remember, in the Java SE world, an archive can be a JAR or a directory on the classpath.

In the Java EE world, there are other kind of archives, so more places to put a `beans.xml` file. But basically the rule is the same: the `beans.xml` file should be put in a `META-INF` directory. There is one exception to this rule though. In the case of a WAR archive, the `beans.xml` file can also be put in the `WEB-INF` directory directly.

What probably comes to mind now is the following question: what happens if you have more than one `beans.xml` file in the set of all the JARs that compose your application? The answer is quite simple, and there are indeed error cases, that we are going to see.

In both the Java SE and Java EE cases, as long as an archive (in the Java sense) has only one `beans.xml` file, everything will be handled properly. An error case can be raised if a configuration has more than one `beans.xml` file in one given archive.

==== The Web archive (WAR) case

The case of the WAR is quite complex, since there are several places where the `beans.xml` can be put. Usually a WAR relies on home made classes, that can be packaged in JAR files put in the `WEB-INF/lib` directory, or put directly in the `WEB-INF/classes` directory. Thus it is logical to enable to put the `beans.xml` file in the `META-INF` directory of the `WEB-INF/classes` directory.

For some reasons, since the `WEB-INF` directory of a WAR is also a place where metadata is put for this web archive, you can also put your `beans.xml` file there.

In a nutshell, the `beans.xml` can be put:

* in the `WEB-INF` directory
* in the `WEB-INF/classes/META-INF` directory
* in the `META-INF` directory of any JAR put in the `WEB-INF/lib` directory.

If a `beans.xml` file is found in the `WEB-INF/classes/META-INF` directory or the `WEB-INF` directory, then the `WEB-INF/classes` is considered a bean archive by CDI. The classes from this directory will be analyzed by the CDI container.

If two `beans.xml` are found in both the `WEB-INF` directory and the `WEB-INF/classes/META-INF` directory, then non-specified behavior will occur. An error may be raised. As a web archive designer, you should not be doing that.

Of course, any JAR from the `WEB-INF/lib` that contains a `beans.xml` file in its `META-INF` directory is a bean archive.


==== The Enterprise archive (EAR) case

An Enterprise Archive can contain any kind of archive previously defined: JAR, WAR or RAR. Some of those JAR have a special semantic: they are called EJB JAR.

All the previous rules stand for the archives that an EAR depends on.

The EJB JAR files need to have a `beans.xml` file to be considered as bean archives and thus analyzed by the CDI container.

There is no `beans.xml` file defined at the EAR level.

==== The EJB JAR case

An EJB JAR is a special kind of JAR that contains EJBs. It can contains a descriptor file: the `ejb-jar.xml` file. This file has been made optional in EJB 3.0, since the information is contains can now be setup in the EJB annotations.

If this file is present, it should be put in the `META-INF` directory of the EJB JAR archive.

Normal rules apply to this archive. Thus, it is a bean archive if it has a `beans.xml` file in its `META-INF` directory. In that case, the content of this archive, and all the archives it depends on will be analyzed by the CDI container.

==== The Connector archive (RAR) case

A RAR archive file contains Java EE connectors used to access enterprise information system. Typically, one such connector exists for each type of resource needed by a Java EE resource. The architecture of the Java EE platform defines the notion of Java EE Connector, the Java EE standard for such adapter components. Those components are packaged in a special archive file: the RAR file.

In this case, the CDI container looks for all the JAR that this RAR depends on. All the previous rules stand in telling if a JAR is a bean archive or not.

There is no `beans.xml` file defined at the RAR level.

==== Embedded EJB

An embedded EJB container uses a system property called `javax.ejb.embeddable.modules`. This property works as a classpath, and defines all the archives this EJB container depends on. If this property is not defined, then the classpath is used instead of this property.

In the case of an embedded EJB container, all the java archives are seen as bean archives.


==== What happens if a class is present in more than one archive?

Enterprise applications may be so complex that it becomes more and more frequent to have classes present in more than  on archive. This is especially true for outside dependencies. It is nor rare to see a given library present more than once in the dependency tree of an application, sometimes with different version numbers!

If a class is present in more than one bean archive, then non defined behavior will occur. You may have different behaviors with different CDI implementations. In one word: avoid this case at all cost!

