
=== What is a CDI bean?

Now that we saw the concept of bean archive, and the role of the `beans.xml` file, we can move to the next notion: the CDI bean.

The concept of CDI bean is as important as the concept of bean archive. It is central, and needs to be properly explained before going further into the presentation of CDI.

In a nutshell, a CDI bean is a basic Java bean that CDI knows about and can handle. Handling here means many things: from what we already know, CDI can build and inject a CDI bean.

In this paragraph, we define several key notions: the type of a CDI bean, the lifecycle of a CDI bean, and the definition of a CDI bean.

==== The type of a CDI bean

First, a bean is a Java object. So, as all Java objects, it has a type. From this point of view, there is no difference between a plain Java object and a CDI bean. Through the Java inheritance type system, any object can have several types: classes and interfaces. Of course CDI relies on the Java standard type system. So a CDI bean has all the types a Java bean has.

Now, for some reasons that we have not seen yet, the type of a bean in the CDI sense is much more complex than the type of a regular Java bean.

We will see all the details on CDI types in a paragraph later in this chapter. So let us carry on with this simple idea for now, that the type of a CDI bean is the same as the type of a Java bean.

==== The lifecycle of a CDI bean

The second important point is that a CDI bean is provided by a CDI container. You should not create a bean by yourself in a CDI application. Merely, you should make a request on the CDI container to get an instance of a bean, just as in the factory pattern. In fact, CDI implements the factory design pattern on this point. This request can be implicit. This is what you did in the first example you wrote, using the `@Inject` annotation.

There are two consequences of that. The first one is that a bean is bound to the CDI container that created it. The second is the notion of lifecycle. A CDI bean has a lifecycle, from its creation to its destruction, composed of several steps. Each step has its own callback which allows a very fine control on the building of CDI beans, with many possibilities for your applications.

// TODO José : diagramme pour le cycle de vie

==== What is a managed bean?

// TODO Antoine : consolider la notion de managed bean
So a bean is an instance of a Java object, provided by a container (the CDI container). It can also be called a managed bean, since the container takes care of the creation and destruction of this bean. The container provides many things for beans. For instance, it can see that a method is called, thus allowing the interception of this call.

In the Java EE context, and for backward compatibility reasons, some special types of beans have been defined in the CDI context. We will see these beans in further details, let us just mention them here.

// TODO Antoine : consolider cette liste
* All the Java EE resources defined at the Java EE container level are exposed as managed beans. This is basically any resource accessible through the Java Naming Directory Interface (JNDI). It includes for instance data sources, Java Messaging System (JMS) queues, and also any global variable. Some of those resources may also be accessible through other means.
* Persistence units and persistence contexts, which are defined by the JPA specification, are exposed through special managed beans. A persistence unit bean is of type `EntityManagerFactory`, and a persistence context bean is of type `EntityManager`. In the Java EE context, an `EntityManager` is bound to a transaction.
* EJBs are also managed beans in the Java EE context. EJB are defined in their own Java EE specification, and carry special semantics regarding how their methods are called.
* Web services are the last special type of managed beans handled by CDI in the Java EE context.

==== Defining CDI beans, metadata

Defining a basic CDI bean is a very simple process. But there are many refinements that can be done: decoration, interception, specialization just to name a few. The overall process becomes more an more complex as we go deeper and deeper in the many functionalities offered by CDI. We are not going to see them all in this paragraph, but present them one by one later in this book.

