
=== Injection points

// Todo Antoine Antoine : digramme pour expliquer l'injection de dépendances

We had a first glimpse at what dependency injection is in CDI: a field of a bean was annotated with `@Inject` in our first example, and we saw that CDI just put an instance of the right type in that field. It worked quite magically, but there is in fact no magic behind that. CDI could find a bean definition of the right type, and could wire this injection point and this bean together. CDI used this annotation to create a bean and store it in the annotated field.

Let us see more details about this `@Inject` annotation right now, because we are going to use it a lot in the rest of this book. We need to keep in mind the context in which CDI will use this annotation.

At some point, CDI needs to create an instance of a bean. If this bean as a state, that is, if it has fields, then CDI needs to check if those fields need be initialized with some values. To tell that, it will look for this `@Inject` annotation.

The first example we saw is probably the simplest one: putting `@Inject` on a field. CDI will find how to build a bean of the right type to match the one of this field, create an instance of this bean, and store it in the field. Easy and simple.

There are other possibilities for where we can add this `@Inject` annotation. Let us have a look at the definition of this annotation.

[[app-listing]]
.The definition of the `@Inject` annotation
[source,java]
----
@Target({ElementType.METHOD,
         ElementType.CONSTRUCTOR,
         ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface Inject {
}
----

This annotation can be put on fields (and indeed we saw that), but it can also be put on constructors and methods. What does it mean to inject a constructor or a method?

==== A constructor annotated with `@Inject`

In fact, annotating a constructor with `@Inject` tells CDI that it can use that constructor to build an instance of this bean. We wrote previously that a bean needed its empty constructor to be built by CDI using the Java reflection API. This is the case most of the times, but there are cases where we can tell CDI to build beans in other ways, and this is one of them. There are limitations though, since only one constructor can be annotated in that way.

All the parameters of this constructor (it can have more than one) will have to be resolved by CDI. In other words, CDI will have to build instances of the right type for each of those parameters.

==== A method annotated with `@Inject`

What does it mean to put the `@Inject` annotation on a method? There are several cases to consider.

Methods annotated with the `@Inject` annotation become _initializer_ methods. It means that CDI uses these methods to initialize each instance of this class it creates.

A given class may have any number of initializer methods. An initializer method can be private, protected, public or package protected. It cannot be abstract, and certainly not static.

We can have as many initializer methods as we want. Any method with any number of parameters can be an _initializer_ method. As it is the case for the annotated constructor, all the parameters of these method have to be resolved and injected by CDI.

The simplest case is a setter method. In this case, it really looks like annotating the corresponding field, the only difference being: in that case CDI calls the setter instead of setting the value of this field directly using the Java Reflection API.

==== How does CDI creates a CDI bean before injecting it?

// TODO Antoine José : ajouter un graphe

CDI follows a very precise process when it needs to create a particular CDI bean.

First, it calls either the empty constructor of this bean, or its only annotated constructor. Remember, `@Inject` cannot be put on more that one constructor for a given class. This process can imply the injection of other beans as parameters of this constructor.

Second, it injects all the annotated fields.

Third it calls all the initializer methods, injecting the proper beans as parameters of these methods.

The `@Inject` annotation plays a crucial role in this process.

==== Wrap-up on the `@Inject` annotation

The `@Inject` annotation can be put on three elements:

* fields,
* one constructor per class,
* any number of methods (including zero), that become _initializer_ methods.

In all cases, CDI needs to resolve the parameters of the methods it calls. If it cant, then an error will be raised.

We can see that injection can take place on two kinds of elements:

* explicit elements: fields annotated with `@Inject`
* implicit elements: parameters of annotated constructors and methods.