
=== Writing a `beans.xml` file

The previous paragraph was about defining the notion of bean archive in the CDI sense. We saw that it relies on the presence a special file, the `beans.xml` file in the `META-INF` directory. Without this `beans.xml` file, our CDI application was not working at all. Now that we understand the role this file plays in a CDI application, let us see what you should put in it.

This paragraph covers the content of the `beans.xml` file, and how this content evolved from the 1.0 version to the 2.0 version.


==== The `beans.xml` file in CDI 1.0

The `beans.xml` is a very simple XML file. In CDI 1.0 it has the following format.

[[app-listing]]
[source,xml]
.An empty `beans.xml` file in CDI 1.0
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://java.sun.com/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
                           http://java.sun.com/xml/ns/javaee/beans_1_0.xsd">
</beans>
----

The namespace is `http://java.sun.com/xml/ns/javaee` and the schema location is `http://java.sun.com/xml/ns/javaee/beans_1_0.xsd`. It is important to note that, because it changed in CDI 1.1 and later.

==== The `beans.xml` file in CDI 1.1 and later

Be careful, because between version 1.0 and 1.1 something odd happened: both the namespace of the root element of this file and the schema location have been changed. So if you need to migrate a CDI 1.0 application to a more recent version, you need to check your `beans.xml` files. Let us have a look at those new values right now.

Note also that there is no specific schema for CDI 1.2 (`beans_1_2.xsd`). CDI 1.2 is a maintenance release, the schema has not been modified.

[[app-listing]]
[source,xml]
.A second beans.xml file for CDI 1.1 and CDI 1.2
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
                           http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"

       bean-discovery-mode="annotated"
       version="1.1">
</beans>
----

==== The version and bean discovery mode attributes

The root element of this `beans.xml` file is `beans`. In CDI 1.0 it has no attribute defined. This changed in CDI 1.1, where two attributes were introduced:

* `version`, set to 1.1 by default;
* `bean-discovery-mode`, which has no default value and is mandatory.

This `bean-discovery-mode` may take three values: `annotated`, `all` and `none`. Let us see that in details.

The bean discovery mode `none` means that no type from this archive will be analyzed. This bean archive does exist, but you are telling CDI that it is empty. 

The bean discovery mode `annotated` means that only the annotated types will be considered by CDI. This is the recommended value. It just works as you expect it. All your annotated beans will be taken into account by the CDI container.

The last mode is the `all` mode and you should be very careful with it, because all the types in the archive will be used by the CDI container. So if you have crafted your archive very carefully and you know that indeed all your types are CDI types, then you can use it. In all the other cases, use the `annotated` mode.

There are no other attributes added to this `beans` element.

==== Subelements of the `beans` root element

CDI defines several subelement to this `beans` root element. We are not going to see them right now. Presenting the list of those subelements here whould not make sense, since we do not know the concepts they define. We will see them one by one throughout this book, one at a time.
