
=== Advanced concepts in qualifying bean

There are two concepts we need to go through on the topic of the CDI Bean Type system. Those two concepts are `@Alternative` and `@Specializes`. These concepts are quite complex, but in some vey precise cases, needed in CDI applications.

==== Introduction

Suppose we have a working CDI application with many producers and injection points. Everything was very carefully designed and written, and the application heavily relies on qualifiers to associate producers and injection points.

And for some reason, testing, debugging, you name it, we need to substitute a given bean of a given type with another bean. The Java type of this second bean is different, but the qualifiers are the same. We want to provide a class that should be used by CDI to create a given bean, and inject everywhere in our application instead of the first one. This can become a real nightmare to do, especially if our application is large an complex.

The solution cannot rely on adding some kind of information (qualifier for instance) on the injection points. First it would be very error prone (suppose we forget one). And it would also be very complex, this would not lead to a reliable solution.

Plus, since CDI offers the possibility to get an instance of a bean programmatically, a point that will be fully described at the end of this chapter. This possibility makes this solution a non-solution, since it will fail with programmatic lookup.

So the only reliable way to do that is to act on the producing side. An approach one could think of could be to create a class with the exact same Java types. The simplest way to do that is to extend the class we want to substitute and the same qualifiers to it. But by doing that, we would create an ambiguity in our CDI application, since we would define two beans with the same CDI Bean Type. We cannot add a special qualifier to it, since we would then need to add this qualifier everywhere on the injection side, a solution that we discarded.

This is exactly for this kind of situation that the `@Alternative` concept has been created in CDI. The bean we want to substitute to the normal, injected bean, is declared as the _alternative_ of the normal bean, and then, CDI will magically inject this alternative in place of the normal bean.

==== Creating an alternative bean

===== The `@Alternative` annotation

From a technical point of view, creating an alternative bean is really simple. We just need to add the `@Alternative` annotation where the bean is produced and we are done.

[[app_listing]]
.Declaring the `InMemoryConcurrentPostRepository` class as an alternative using an annotation
[source,java]
----
package chap04.repository;

import javax.enterprise.inject.Alternative;

@Alternative
public class InMemoryConcurrentPostRepository implements PostRepository, Serializable {

    // content of the class
}
----

===== Annotation versus XML declaration

Adding an annotation is very simple, but it requires the compilation of the class where we added the annotation. We must consider two cases here.

The first one is the case where this alternative class is a separate class, created for this case. Adding this annotation to this class is the natural way of doing it. If this class is a test class, it will not be deployed at runtime. If this class is some temporary class that we need to add to our application for debugging or auditing purposes, then we can put it in a separate JAR and remove that JAR when we do not need it anymore. In both cases, we do not need to recompile all our application to declare this alternative.

The second case is a bit more complex. We want a class that is already in our application to become the alternative. If we decide to add this annotation to it, then we will need to recompile everything, and go through all the testing and deployment process. This way might be costly, too costly for our needs.

Instead of doing it that way, we can also add the declaration of alternatives in the `beans.xml` file. Using this way, we do not need to recompile our application, we only need to redeploy it with the modified `beans.xml`file. It is good to keep in mind this way of modifying the configuration of Java EE elements, since it may prove much more efficient than having to recompile and rebuild everything.

Declaring an alternative in the `beans.xml` configuration file is really easy. Let us see the following example.

[[app_listing]]
.Declaring the `InMemoryConcurrentPostRepository` class as an alternative in the `beans.xml`configuration file
[source,xml]
----
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
                           http://xmlns.jcp.org/xml/ns/javaee/beans_2_0.xsd">

   <alternatives>
      <class>chap04.repository.InMemoryConcurrentPostRepository</class>
   </alternatives>
</beans>
----

All we need is to declare the alternative class in the `alternatives` XML subelement of the `beans` element.

===== More than one bean annotated with `@Alternative`

It is possible to have more than one bean with the same CDI Bean Types annotated with `@Alternative`. Of course this case will raise errors due to ambiguities in the resolution of which of those beans should be used to injection. Referencing one of these classes in the `beans.xml` file will resolve the ambiguity.

===== Selecting an alternative bean with the `@Priority` annotation

There is also another way to choose from several beans annotated with `@Alternative`. This way consists in adding a `@Priority` annotation along with the `@Alternative` annotation. This annotation will make this bean the chosen one among the other alternatives. The `@Priority` annotation takes an `int` attribute that has no default value. So we must give a value to this priority.

The `@Priority` annotation does not come rom CDI. It comes from `javax.annotation`, and its exact meaning is left to the specifications that use it. CDI does indeed mention it for alternatives, but does not give precision on the way this attribute is used. So far we assume that only one alternative can be annotated with `@Priority`.


===== Alternative use cases

Alternatives are a very powerful tool that can be used in several use cases.

The first one of course is when we need to inject mock objects in a testing environment. Declaring our mock class as an alternative makes it very easy to inject this mock object instead of the runtime bean. The mocked class is only known in the test context, and will not be deployed at runtime (if it is the case, fix it!). So all we need to do if to extend the class of the real bean, sparkle some mocking magic on it, put the same qualifiers on this class, and add declare it as an alternative, either by annotating it, or by declaring it in the `beans.xml` file.

But we can also imagine other use cases. Suppose our application is internationalized. We could imagine having a bunch of supported locales, each represented by sets of classes, put in different packages. These classes are in fact models for CDI beans, and are meant to be injected, or are referenced by JSF templates. One way of organizing this is to set the correct set of class as the alternative in a given deployment scenario using a given locale.

==== Creating a `@Specializes` bean

In a nutshell an alternative bean is a way to override a bean with another one. Inside this mechanism there are two ways to resolve further ambiguities. But unfortunately, there are still cases where alternatives are not enough to override a given bean definition.

Remember that an alternative is selected as a bean only if both CDI Bean Type are the same. Let us consider the following example.

We are still dealing with our in-memory `PostRepository`. So we have this interface `PostRepository`, and two implementing classes, `InMemoryPostRepository` and `InMemoryConcurrentPostRepository`. We learned about qualifiers and decided to further explain the difference between those two implementations by putting a `@Concurrent` annotation on the `InMemoryConcurrentPostRepository` implementation.

So the declaration of these two classes is the following.

[[app_listing]]
.Declaring the `InMemoryConcurrentPostRepository` class with the `@Concurrent` qualifier
[source,java]
----
package chap04.repository;

@Concurrent
public class InMemoryConcurrentPostRepository implements PostRepository {

    // content of the class
}
----

[[app_listing]]
.Declaring the `InMemoryPostRepository` class
[source,java]
----
package chap04.repository;

public class InMemoryPostRepository implements PostRepository {

    // content of the class
}
----

The `@Concurrent` annotation is just a basic qualifier.

Now, for testing purposes, we decide to extend the `InMemoryConcurrentPostRepository` class with a mocking class: `MockInMemoryConcurrentPostRepository`. The definition of this last class is the following.

[[app_listing]]
.Declaring the `MockInMemoryConcurrentPostRepository` class
[source,java]
----
package chap04.repository;

public class MockInMemoryConcurrentPostRepository extends InMemoryConcurrentPostRepository {

    // content of the class
}
----

This is our setup for the definition of the beans we are going to use.

Of course, we have many injection points for these post repositories in our application. Let us see a first one, that just needs a `PostRepository`.

[[app_listing]]
.Declaring an injection point for a post repository
[source,java]
----
@Inject
private PostRepository repository;
----

What is going to happen with our setup? Well, CDI will first register the beans that can be injected in this field. It will find 3 of them: `InMemoryPostRepository`, `InMemoryConcurrentPostRepository` and `MockInMemoryConcurrentPostRepository`. And since CDI has no information to tell which implementation should be used, an error will be raised. We need to fix our code. This is the classical ambiguity we already talked about.

Thanks to our hard work in trying to learn CDI, we know that we have this `@Alternative` annotation that we can add on a type to resolve ambiguities. This is what we do: we add the `@Alternative` annotation on the declaration of `MockInMemoryConcurrentPostRepository`. And indeed it fixes the ambiguity, our testing code is running smoothly.

But then we realize that when this mocking class is not there anymore, the ambiguity is still there: CDI cannot tell from `InMemoryRepository` and `InMemoryConcurrentRepository`. Basically our test was running smoothly, but in production it did not work, due to the fact that this alternative is not there anymore.

We then need to resolve this ambiguity again. We could use `@Alternative` again, but we prefer to add the `@Concurrent` qualifier on our injection point, since this is what our code needs. This approach is the best one, since is makes our code more readable. This time, our injection point looks like the following.

[[app_listing]]
.Declaring an injection point for a concurrent post repository
[source,java]
----
@Inject @Concurrent
private PostRepository repository;
----

Indeed, this annotation fixes our code in production, since the injected bean has to have the `@Concurrent` qualifier.

And then we realize that our test code does not work anymore! The `MockInMemoryConcurrentPostRepository` is not injected; the test code still injects the`InMemoryConcurrentPostRepository`. Why so? Simply because the qualifiers are not inherited. The `MockInMemoryConcurrentPostRepository` does not have the qualifier `@Concurrent` and thus is not a candidate for injection here. This will probably not look natural for many people, but logical with all the rules we have written and used so far.

Let us have a look back at we did exactly. What are we doing here? We have to classes `A` and `B`, with `B`extending `A`. We extend a class, add the `@Alternative` annotation on it thinking that it will fully override the class we extend, and in fact it does not, because the annotations are not inherited.

Most of the time this is not what we want. This is precisely to overcome this problem that the specialization has been added to CDI. In a nutshell, adding the `@Specializes` annotation to the overriding class will do the trick: CDI will take it in place of the overridden class, wherever this class is used.

When a bean _specializes_ another bean then we are sure that this other bean is not used as a bean by CDI. It is not seen, not instantiated, nothing.

For a bean to be a specialization of another bean, either its class must directly extends the class of this other bean, either its producing method must directly override the producing method of the first bean. Then the `@Specializes` annotation must be added to the class or to the producing method, as the case may be. Note that it the producer is in fact a field, no specialization can be set up, since a field cannot be overridden.

This specialization has a side effect, which is probably the desired effect in most cases. If the original bean declares itself one or several producing methods, or observers, those will not be seen by CDI, and thus not activated. Once again, this is probably what we want, since specialization will be used, most of the time, in a testing environment.
