:sourcedir: ../../code/src/main/java

[[chap04-getting-started]]
== Getting started with CDI

As we saw, CDI in itself is a specification, that is an abstract concept, or a set of abstract concepts, described in a paper document. Aside of this document, there are several implementations that are there to give life to this specification.

What does this specification do? Well, it defines many things, many concepts, and the way those concepts interact between themselves. The interactions between those concepts are many, and to understand the overall, you need to know CDI well. Basically, to understand CDI, you need to have a good understanding of CDI, which is a good example of the chicken and egg problem.

So before deep diving in all these abstract and complex concepts, let us write a first, very simple application. This application will have a `beans.xml` file, an injection point, and we are going to run it in a Weld container. A Weld container is the piece of software we need to run a CDI application. Weld is an implementation of the CDI specification, it has a special status among all the existing implementations: it is the reference implementation.

include::2_04/2-04-01-writing-you-first.adoc[]
include::2_04/2-04-02-the-content-of-beans.adoc[]
include::2_04/2-04-03-bean-archive.adoc[]
include::2_04/2-04-04-concept-of-a-bean.adoc[]
include::2_04/2-04-05-where-do-we-go.adoc[]
include::2_04/2-04-06-injection-point.adoc[]
include::2_04/2_04-07-producing-beans.adoc[]
include::2_04/2_04-08-more-on-the-type-of-a-bean.adoc[]
include::2_04/2_04-09-using-qualifiers.adoc[]
include::2_04/2_04-10-advanced-concepts-in-qualifiying.adoc[]


=== Getting more flexibility with Programmatic lookup

* @Any
* Instance<T>
* AnnotationLiteral, TypeLiteral

=== Using @Stereotype to simplify @Alternative
=== Wrap-up

